name: ewallet
description: New 9Pay application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 3.1.3+326
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_screenutil: ^3.1.1
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_logging: ^0.5.0
  dio: ^4.0.0
  flutter_spinkit: ^5.0.0
  image_sequence_animator: any
  azlistview: ^1.1.1
  flutter_animator: ^3.1.2
  open_store: ^0.2.4
  flutter_bounce: ^1.1.0
  carousel_slider: ^4.0.0
  asset_cache: ^1.0.0+1
  sticky_headers:
  vibration: ^1.7.3
  contacts_service: any
  flutter_swiper_plus: ^2.0.4
  animated_background: ^2.0.0
  flutter_svg: ^0.22.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.2
  device_info_plus: ^2.1.0
  package_info: ^2.0.2
  uuid: ^3.0.4
  flutter_inappwebview: ^5.3.2
  local_auth: ^1.1.6
  bordered_text: ^2.0.0
  bot_toast: ^4.0.1
  easy_mask: ^2.0.1
  flutter_staggered_animations: ^1.0.0
  route_observer_mixin: ^1.5.0+1
  flutter_keyboard_visibility: ^5.0.3
  lottie: ^1.1.0
  shimmer: ^2.0.0
  auto_size_text_field: ^0.1.7
  auto_size_text: ^3.0.0
  after_layout: ^1.1.0
  flutter_html: ^2.1.1
  webview_flutter: ^2.0.10
  flutter_local_notifications: ^8.0.0
  badges: ^2.0.1
  cupertino_icons: ^1.0.3
  url_launcher: ^6.0.3
  share: ^2.0.4
  npay_component: ^0.1.9
  cached_network_image: ^3.1.0
  sqflite:
  path: ^1.8.0
  just_audio: ^0.9.5
  http_parser: ^4.0.0
  age: ^0.0.1
  dotted_border: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  email_launcher: ^1.1.1
  pull_to_refresh: ^2.0.0
  flutter_secure_storage: ^4.2.1
  flutter_cupertino_localizations: ^1.0.1
  permission_handler: ^6.0.1+1
  flutter_native_image: ^0.0.6+1
  flare_flutter: ^3.0.2
  crypto: ^3.0.1
  graphql_flutter: ^5.0.0
  qr_flutter: ^4.0.0
  app_settings: ^4.1.1
  flutter_device_type: ^0.4.0
  email_validator: ^2.0.1
  cloud_firestore: ^2.4.0
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_analytics: ^8.2.0
  firebase_dynamic_links: ^2.0.7
  firebase_database: ^7.2.1
  screenshot: ^1.2.3
  image_picker: ^0.8.3+2
  hashids2: ^2.0.0
  qr_code_tools: ^0.0.7
  pin_code_fields: ^7.3.0
  pretty_dio_logger: ^1.1.1
  page_transition: ^2.0.2
  appsflyer_sdk: ^6.2.4+4-nullsafety
  add_2_calendar: ^2.1.0
  #  camera: ^0.7.0+4
  # waiting camera fix bug timeout
  camera:
    git:
      url: https://github.com/tnvinh2711/plugins
      path: packages/camera/camera
  safe_device: ^1.0.7
  flutter_native_splash: ^1.2.1
  social_share_plugin: ^0.3.1+1
  visibility_detector: ^0.2.0
  connectivity: ^3.0.6
  flutter_slidable:
  qr_code_scanner: ^0.5.2
  flutter_localizations:
    sdk: flutter
  diacritic: ^0.1.3
  share_files_and_screenshot_widgets_plus: ^1.0.3
  flutter_page_transition: ^0.1.6
#  event_calendar:
#    path: ./event_calendar
  firebase_crashlytics: ^2.1.1
  otp_listener: ^0.0.3
  flutter_bloc: ^7.3.0
  readmore: ^2.1.0
  html_unescape: ^2.0.0
  images_picker: ^1.2.4
  swipe: ^0.0.1
  dio_http_cache: ^0.3.0
  async: ^2.6.1
  equatable: ^2.0.3
  image_gallery_saver: ^1.7.0
  scrollable_clean_calendar: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
#  assets:
#    - assets/
#    - assets/images/
#    - assets/fonts/
#    - assets/svg/
#    - assets/sql/
#    - assets/animations/
#    - assets/flr/
#    - assets/audio/
#    - assets/breaking_eggs/animations/
#    - assets/breaking_eggs/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#    - family: TeddyBear
#      fonts:
#        - asset: assets/fonts/TeddyBear-Bold.ttf
#          weight: 700
#    - family: SVN
#      fonts:
#        - asset: assets/fonts/SVN-Poppins-SemiBold.ttf
#          weight: 900
#        - asset: assets/fonts/SVN-Poppins-SemiBold.ttf
#          weight: 700
#        - asset: assets/fonts/SVN-Poppins-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/SVN-Poppins-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/SVN-Poppins-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/SVN-Poppins-Thin.ttf
#          weight: 300
#    - family: MyFlutterApp
#      fonts:
#        - asset: assets/fonts/MyFlutterApp.ttf
#    - family: SVN-Poppins
#      fonts:
#        - asset: assets/fonts/SVN-Poppins-SemiBold.ttf
#          weight: 900
#        - asset: assets/fonts/SVN-Poppins-SemiBold.ttf
#          weight: 700
#        - asset: assets/fonts/SVN-Poppins-Medium.ttf
#          weight: 400
#        - asset: assets/fonts/SVN-Poppins-Regular.ttf
#    - family: Nunito
#      fonts:
#        - asset: assets/fonts/Nunito-Black.ttf
#          weight: 900
#    - family: Phosphate
#      fonts:
#        - asset: assets/fonts/Phosphate.ttf
#          weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


#flutter_native_splash:
#  background_image: assets/images/splash_background.png
#  android_gravity: bottom
#  ios_content_mode: bottom
#  android12: true
